Work in progress Quat animation
mcpar-land/bevy pull request #1
Opened 2020-10-27 10:27 UTC by iwikal

This is what I have so far. The `Rotation` shim is exposed to the public API, which isn't super desirable, but it shows the functionality, at least.

2020-11-26 16:14 UTC, mcpar-land commented
Be sure to merge my 0.3 update for this! I'll happily merge it when it's done

2020-11-26 22:11 UTC, iwikal commented
I can't explain why the CI is failing - neither of us wrote that.

2020-11-29 20:20 UTC, mcpar-land requested changes

2020-11-29 20:20 UTC, mcpar-land commented on crates/bevy_animation/src/spline_group.rs
> +    fn spline_key_times(&self) -> Vec<Box<dyn DoubleEndedIterator<Item = f32> + '_>>;
- I think we should leave the `splines` function available for general use alongside your new `spline_key_times` function, rather than replacing it.

- Dunno about returning a `Vec` containing arbitrary iterators. Consider adding another `type` to the `SplineGroup` trait instead?

```rust
pub trait SplineGroup {
  type Sample;
  type KeyTimes;

  fn spline_key_times(&self) -> KeyTimes;

  // ...

}

impl SplineGroup for AnimationSplineOne {
  type Sample = Option<f32>;
  type KeyTimes = Box<dyn DoubleEndedIterator<Item = f32> + '_>;
  
  // ...

}
```

2020-11-29 21:37 UTC, iwikal commented on crates/bevy_animation/src/spline_group.rs
> +    fn spline_key_times(&self) -> Vec<Box<dyn DoubleEndedIterator<Item = f32> + '_>>;
The thing is, there can no longer be an `fn splines(&self) -> Vec<&Spline<f32, f32>>` on SplineGroup, since not all splines have f32 values - one of them has Quats instead. So I looked around to see what the splines method was used for internally, replaced it with spline_key_times, and didn't really think too hard about how people might want to use it in general. I kind of assumed that it was just a side effect of needing to use it internally, and not having private trait methods. What's the use case?

I was absolutely not pleased with returning a Vec<Box<dyn Iterator>>, but I just wanted to get a proof of concept working. Now that you've brought it back to my attention, I would like to look into if there's a better way to implement start_time, end_time and is_empty on SplineGroup, which to my knowledge are the only things spline_key_times is used for. Maybe we could just leave them as required methods, instead of trying to create a general default implementation that will probably end up needing dynamic dispatch?

2020-11-29 22:50 UTC, mcpar-land commented on crates/bevy_animation/src/spline_group.rs
> +    fn spline_key_times(&self) -> Vec<Box<dyn DoubleEndedIterator<Item = f32> + '_>>;
> The thing is, there can no longer be an fn splines(&self) -> Vec<&Spline<f32, f32>> on SplineGroup, since not all splines have f32 values - one of them has Quats instead.

Ah, true that.

> What's the use case?

main one I thought of is that if this is eventually integrated into a UI, you'd want direct access to the splines for drawing them in a curve editor.

> Maybe we could just leave them as required methods, instead of trying to create a general default implementation that will probably end up needing dynamic dispatch?

Seems like a good option. Feel free to experiment.


It's worth mentioning that there's [Another PR doing animation](https://github.com/lassade/bevy/tree/animations/crates/bevy_animation) that uses property names and just seems overall more flexible than the hard-typed implementation we're doing here. It might be a better option entirely.

2020-11-30 20:03 UTC, iwikal commented on crates/bevy_animation/src/spline_group.rs
> +    fn spline_key_times(&self) -> Vec<Box<dyn DoubleEndedIterator<Item = f32> + '_>>;
> It's worth mentioning that there's [Another PR doing animation](https://github.com/lassade/bevy/tree/animations/crates/bevy_animation) that uses property names and just seems overall more flexible than the hard-typed implementation we're doing here. It might be a better option entirely.
Wow, I hadn't seen that. I'm looking through it now, trying to understand what they're doing.

2020-11-30 20:44 UTC, iwikal commented
The failing CI is due to a new clippy warning that they have already suppressed in master. It will go away on its own after merging.

2020-11-30 20:58 UTC, mcpar-land approved these changes

2020-11-30 20:59 UTC, merged